#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing 🏗️👷'

# Check prettier
npm run check-format || {
  echo '🤡😂❌🤡 Prettier Check Failed. 🤡😂❌🤡
      Run npm run format, add changes, and try commit again';
  exit 1;
}

# Check ESLint
npm run check-lint || {
  echo '🤡😂❌🤡 ESLint Check Failed. 🤡😂❌🤡 
      Make the required changes listed above, add changes, and try to commit again';
  exit 1;
}

# Check tsconfig
npm run check-types || {
  echo '🤡😂❌🤡 Type Check Failed. 🤡😂❌🤡 
      Make the required changes listed above, add changes, and try commit again';
  exit 1;
}

# Build your project
npm run build || {
  echo '🤡😂❌🤡 Your Build Failed. 🤡😂❌🤡 
      View the error above';
  exit 1;
}

echo "✅✅✅✅ Success Commit... ✅✅✅✅"
